In [1]:
#Amount Paid > 1500 and Payment Method GCash and PayMaya
#Sort highest to lowest Amount Paid
#Calculate the amount paid (total, average, min and max)
#Group total Amount Paid by Payment Method
#Write at least three findings in plain language.

In [150]:
import pandas as pd
import numpy as np

In [151]:
files = {
    "customers": "customers.csv",
    "products": "products.csv",
    "orders": "orders.csv",
    "order_items": "order_items.csv",
    "payments": "payments.csv",
    "shipments": "shipments.csv",
    "returns": "returns.csv"
}

data = {name: pd.read_csv(path)
        for name, path in files.items()}

for name, df in data.items():
    print(name, df.shape)
    print(df.isna().sum().sort_values(
        ascending=False).head())
    print("duplicates:", df.duplicated().sum())

customers (5050, 13)
gender          301
loyalty_tier    266
age             150
phone           147
email           107
dtype: int64
duplicates: 50
products (800, 9)
stock_qty       19
product_id       0
product_name     0
category         0
brand            0
dtype: int64
duplicates: 0
orders (15075, 8)
discount_pct    758
shipping_fee    474
order_id          0
customer_id       0
order_status      0
dtype: int64
duplicates: 75
order_items (37763, 5)
unit_price_at_purchase    2262
order_item_id                0
order_id                     0
product_id                   0
quantity                     0
dtype: int64
duplicates: 262
payments (15000, 6)
amount_paid       878
payment_id          0
order_id            0
payment_method      0
payment_status      0
dtype: int64
duplicates: 0
shipments (15000, 7)
delivered_date    729
order_id            0
shipment_id         0
courier             0
tracking_no         0
dtype: int64
duplicates: 0
returns (1200, 6)
refund_amount    187
refunded_flag    110
order_id           0
return_id          0
reason             0
dtype: int64
duplicates: 0

In [152]:
print('hello world')

hello world

In [153]:
import pandas as pd

In [154]:
files = {
    "customers": "customers.csv",
    "products": "products.csv",
    "orders": "orders.csv",
    "order_items": "order_items.csv",
    "payments": "payments.csv",
    "shipments": "shipments.csv",
    "returns": "returns.csv",
}

data = {name: pd.read_csv(path)
        for name, path in files.items()}

for name, df in data.items():
    print(name, df.shape)
    print("=============")
    print(df.isna().sum().sort_values(
        ascending=False).head())
    print("duplicates:", df.duplicated().sum())
    print(df.dtypes)
    print()

customers (5050, 13)
=============
gender          301
loyalty_tier    266
age             150
phone           147
email           107
dtype: int64
duplicates: 50
customer_id         str
first_name          str
last_name           str
gender              str
age             float64
email               str
phone           float64
region_code         str
region_name         str
city                str
barangay            str
signup_date         str
loyalty_tier        str
dtype: object

products (800, 9)
=============
stock_qty       19
product_id       0
product_name     0
category         0
brand            0
dtype: int64
duplicates: 0
product_id          str
product_name        str
brand               str
category            str
unit_cost       float64
unit_price          str
stock_qty       float64
uom                 str
launch_date         str
dtype: object

orders (15075, 8)
=============
discount_pct    758
shipping_fee    474
order_id          0
customer_id       0
order_status      0
dtype: int64
duplicates: 75
order_id               str
customer_id            str
order_datetime         str
order_status           str
sales_channel          str
shipping_method        str
discount_pct       float64
shipping_fee       float64
dtype: object

order_items (37763, 5)
=============
unit_price_at_purchase    2262
order_item_id                0
order_id                     0
product_id                   0
quantity                     0
dtype: int64
duplicates: 262
order_item_id               str
order_id                    str
product_id                  str
quantity                  int64
unit_price_at_purchase      str
dtype: object

payments (15000, 6)
=============
amount_paid       878
payment_id          0
order_id            0
payment_method      0
payment_status      0
dtype: int64
duplicates: 0
payment_id        str
order_id          str
payment_method    str
payment_status    str
payment_date      str
amount_paid       str
dtype: object

shipments (15000, 7)
=============
delivered_date    729
order_id            0
shipment_id         0
courier             0
tracking_no         0
dtype: int64
duplicates: 0
shipment_id        str
order_id           str
courier            str
tracking_no        str
shipment_status    str
ship_date          str
delivered_date     str
dtype: object

returns (1200, 6)
=============
refund_amount    187
refunded_flag    110
order_id           0
return_id          0
reason             0
dtype: int64
duplicates: 0
return_id                  str
order_id                   str
return_request_date        str
reason                     str
refunded_flag              str
refund_amount          float64
dtype: object

In [155]:
data

{'customers':      customer_id first_name   last_name   gender   age  \
 0     CUST000001      Grace  DelosReyes      NaN  20.0
 1     CUST000002        Ana       Ramos   Female  35.0
 2     CUST000003      Arvin     Navarro     Male  14.0
 3     CUST000004       Kyle      Rivera        F  26.0
 4     CUST000005       Juan     Mendoza     Male  29.0
 ...          ...        ...         ...      ...   ...
 5045  CUST000805      Maria   Fernandez        F  33.0
 5046  CUST001442      Grace      Flores        F  41.0
 5047  CUST001095        Ana        Cruz  Unknown  25.0
 5048  CUST003989        Mia      Garcia        M  17.0
 5049  CUST003706      Faith   Fernandez        M  28.0

                                email         phone  region_code  \
 0     grace.delosreyes95@outlook.com  9.196001e+09   Region III
 1           ana.ramos@companymail.ph  9.026542e+09       CARAGA
 2           arvin.navarrooutlook.com  9.161850e+09          NCR
 3          kyle.rivera13@outlook.com  9.752553e+09   Region III
 4             juan.mendoza@gmail.com  9.350306e+09   Region III
 ...                              ...           ...          ...
 5045   maria.fernandez49@outlook.com  9.755752e+09   Region VII
 5046             graceflores@mailcom  9.253268e+09   Region III
 5047         ana.cruz@companymail.ph  9.218946e+09  Region IV-A
 5048             mia.garcia@mail.com  9.402610e+09   Region III
 5049        faith.fernandez@mail.com           NaN       CARAGA

           region_name          city barangay  signup_date loyalty_tier
 0       Central Luzon       Angeles   Brgy 1   2025-12-31       Bronze
 1              Caraga        Butuan   Brgy 9   2025-02-08       Bronze
 2        Metro Manila         Pasig   Brgy 2   2023-09-10       Bronze
 3       Central Luzon       Angeles   Brgy 1   2024-11-17          NaN
 4       Central Luzon       Angeles   Brgy 9   2023-01-21         Gold
 ...               ...           ...      ...          ...          ...
 5045  Central Visayas     Cebu City   Brgy 2   2023-02-27       Bronze
 5046    Central Luzon       Angeles   Brgy 4   2025-11-27       Bronze
 5047       CALABARZON     San Pablo   Brgy 9   01/26/2025       Bronze
 5048    Central Luzon  San Fernando  Brgy 10  14-Oct-2024         Gold
 5049           Caraga        Butuan   Brgy 2   2024-01-29       Silver

 [5050 rows x 13 columns],
 'products':     product_id            product_name      brand          category  \
 0    PROD00001       KidJoy Beauty 963     KidJoy            Beauty
 1    PROD00002       HomeEase Home 368   HomeEase  Home and Kitchen
 2    PROD00003   FreshCart Fashion 911  FreshCart           Fashion
 3    PROD00004       NovaTech Toys 753   NovaTech              Toys
 4    PROD00005        GlowCo Books 916     GlowCo             Books
 ..         ...                     ...        ...               ...
 795  PROD00796         KidJoy Elec 294     KidJoy              Elec
 796  PROD00797       SunPeak Books 182    SunPeak             Books
 797  PROD00798  NovaTech Groceries 889   NovaTech         Groceries
 798  PROD00799        Acme Fashion 991       Acme           Fashion
 799  PROD00800     NovaTech Sports 419   NovaTech            Sports

      unit_cost unit_price  stock_qty     uom launch_date
 0        44.17       64.5      125.0      pc  2022-01-18
 1        37.18      70.39      131.0     pcs  2022-11-25
 2        46.29     ₱70.26       41.0   piece  2023-09-04
 3        43.66      62.46      149.0     pcs  2023-08-12
 4        64.59      82.02      162.0  bottle  2024-05-12
 ..         ...        ...        ...     ...         ...
 795      83.80     132.12      111.0  bottle  2023-08-15
 796      53.67      62.54      163.0  bottle  2023-01-05
 797      63.54     112.46      155.0     set  2022-08-09
 798      25.27      34.96      169.0  bottle  2024-06-19
 799      70.14     116.39      245.0   piece  07/03/2022

 [800 rows x 9 columns],
 'orders':          order_id customer_id       order_datetime order_status sales_channel  \
 0      ORD0000001  CUST000839  2025-11-07 17:02:00    Cancelled   Marketplace
 1      ORD0000002  CUST002871  09/18/2025 09:13 AM    Completed   Marketplace
 2      ORD0000003  CUST000720  2025-08-08 04:59:00    Completed           Web
 3      ORD0000004  CUST002515  2025-10-14 12:56:00    Completed           Web
 4      ORD0000005  CUST001544  2024-05-30 04:56:00    Completed   Marketplace
 ...           ...         ...                  ...          ...           ...
 15070  ORD0011300  CUST000701  2024-11-17 21:58:00    Cancelled   Marketplace
 15071  ORD0014948  CUST003808    28-Dec-2025 01:01    Completed    Mobile App
 15072  ORD0012066  CUST004052  2025-05-04 06:07:00    Completed           Web
 15073  ORD0012132  CUST002798  2025-04-29 21:11:00    Completed    Mobile App
 15074  ORD0013325  CUST001564  03/14/2024 04:48 PM    Completed   Marketplace

       shipping_method  discount_pct  shipping_fee
 0            Standard         0.074        102.68
 1             Express         0.063          0.00
 2            Standard         0.137        103.83
 3              Pickup         0.005        112.69
 4              Pickup           NaN        111.73
 ...               ...           ...           ...
 15070         Express         0.036         75.40
 15071        Standard         0.019        142.29
 15072        Standard         0.087        107.84
 15073          Pickup         0.062         82.12
 15074        Standard         0.117        135.62

 [15075 rows x 8 columns],
 'order_items':        order_item_id    order_id product_id  quantity unit_price_at_purchase
 0      ITEM000000001  ORD0000001  PROD00513         2                 120.67
 1      ITEM000000002  ORD0000002  PROD00124         2                  83.58
 2      ITEM000000003  ORD0000002  PROD00631         2                  46.96
 3      ITEM000000004  ORD0000002  PROD00136         1                 100.59
 4      ITEM000000005  ORD0000002  PROD00090         1                 109.18
 ...              ...         ...        ...       ...                    ...
 37758  ITEM000037216  ORD0014888  PROD00095         3                  48.27
 37759  ITEM000028576  ORD0011406  PROD00702         1                  46.31
 37760  ITEM000026308  ORD0010493  PROD00358         1                 130.84
 37761  ITEM000020512  ORD0008174  PROD00075         3                  42.93
 37762  ITEM000032925  ORD0013151  PROD00530         1                  106.4

 [37763 rows x 5 columns],
 'payments':        payment_id    order_id payment_method payment_status payment_date  \
 0      PAY0000001  ORD0000001          GCash           Paid   2024-05-09
 1      PAY0000002  ORD0000002            COD           Paid   06/25/2024
 2      PAY0000003  ORD0000003          GCash           Paid   2025-06-10
 3      PAY0000004  ORD0000004        PayMaya         Failed   2025-06-21
 4      PAY0000005  ORD0000005            COD        Pending   06/28/2024
 ...           ...         ...            ...            ...          ...
 14995  PAY0014996  ORD0014996          GCash           Paid   2025-06-07
 14996  PAY0014997  ORD0014997        PayMaya           Paid   2025-12-03
 14997  PAY0014998  ORD0014998  Bank Transfer           Paid   2026-01-05
 14998  PAY0014999  ORD0014999          GCash           Paid   12/19/2025
 14999  PAY0015000  ORD0015000          GCash           Paid   2025-12-14

       amount_paid
 0         2822.72
 1         2499.76
 2         1983.66
 3         1765.99
 4         1477.53
 ...           ...
 14995     1985.86
 14996     1596.22
 14997      836.13
 14998         NaN
 14999     2227.32

 [15000 rows x 6 columns],
 'shipments':       shipment_id    order_id      courier   tracking_no shipment_status  \
 0      SHP0000001  ORD0000001          J&T  HLI2ORMO9V4O       Delivered
 1      SHP0000002  ORD0000002     NinjaVan  E8XLRMV7QVEB      In Transit
 2      SHP0000003  ORD0000003          2GO  LHLXVJF18MQB       Delivered
 3      SHP0000004  ORD0000004  GrabExpress  RXUNTQ7WKL5B       Delivered
 4      SHP0000005  ORD0000005          2GO  XQLUM80WBUSJ      In Transit
 ...           ...         ...          ...           ...             ...
 14995  SHP0014996  ORD0014996     NinjaVan  DSX72VVET6CL       Delivered
 14996  SHP0014997  ORD0014997  GrabExpress  SVSYZ9YKBJYS       Delivered
 14997  SHP0014998  ORD0014998          LBC  DVYT8KX7SF5I       Delivered
 14998  SHP0014999  ORD0014999          J&T  X5P5PWP8DYU0       Delivered
 14999  SHP0015000  ORD0015000          2GO  2VWTGJJS9XHI       Delivered

          ship_date delivered_date
 0       2025-09-05     09/06/2025
 1       2025-02-06     2025-02-12
 2       2025-07-23     2025-07-29
 3       2025-01-21     2025-01-25
 4       2025-09-21     2025-09-26
 ...            ...            ...
 14995   2024-02-21     2024-02-23
 14996   2024-01-27     2024-02-03
 14997   2025-01-25     2025-01-29
 14998   2024-05-22     2024-05-26
 14999  18-Jul-2025     07/19/2025

 [15000 rows x 7 columns],
 'returns':       return_id    order_id return_request_date         reason refunded_flag  \
 0     RET000001  ORD0008752          2025-01-09      Defective            No
 1     RET000002  ORD0007359          2025-07-20     Wrong item           NaN
 2     RET000003  ORD0009041          01/07/2025     Size issue           Yes
 3     RET000004  ORD0000227          2025-03-04  Late delivery       Partial
 4     RET000005  ORD0005754          2025-04-24     Size issue           Yes
 ...         ...         ...                 ...            ...           ...
 1195  RET001196  ORD0008236          2024-11-02     Wrong item           Yes
 1196  RET001197  ORD0011974          10/10/2024  Late delivery            No
 1197  RET001198  ORD0014526          2025-06-25     Size issue       Partial
 1198  RET001199  ORD0011487          2024-02-20  Late delivery            No
 1199  RET001200  ORD0013304          2025-08-12   Damaged item           Yes

       refund_amount
 0               NaN
 1            650.28
 2               NaN
 3               NaN
 4            713.39
 ...             ...
 1195        1094.79
 1196         356.74
 1197         500.08
 1198         171.28
 1199         857.96

 [1200 rows x 6 columns]}

In [156]:
data['customers']['gender'].value_counts(dropna=False)

gender
M          1310
F          1275
Female      731
Male        725
Unknown     593
NaN         301
female      115
Name: count, dtype: int64

In [157]:
data['products']['category'].value_counts(dropna=False)

category
Beauty              94
Toys                92
Books               90
Fashion             89
Groceries           77
Home & Kitchen      76
Sports              74
Electronics         71
electronics         20
Book                20
Home and Kitchen    19
Electronics         17
Grocery             12
Elec                11
Beauty & Care       11
Toy                 11
Fashon               8
Sports & Outdoor     8
Name: count, dtype: int64

In [158]:
customers_clean = data['customers'].copy()

In [159]:
customers_clean

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier
0,CUST000001,Grace,DelosReyes,NaN,20.0,grace.delosreyes95@outlook.com,9.196001e+09,Region III,Central Luzon,Angeles,Brgy 1,2025-12-31,Bronze
1,CUST000002,Ana,Ramos,Female,35.0,ana.ramos@companymail.ph,9.026542e+09,CARAGA,Caraga,Butuan,Brgy 9,2025-02-08,Bronze
2,CUST000003,Arvin,Navarro,Male,14.0,arvin.navarrooutlook.com,9.161850e+09,NCR,Metro Manila,Pasig,Brgy 2,2023-09-10,Bronze
3,CUST000004,Kyle,Rivera,F,26.0,kyle.rivera13@outlook.com,9.752553e+09,Region III,Central Luzon,Angeles,Brgy 1,2024-11-17,NaN
4,CUST000005,Juan,Mendoza,Male,29.0,juan.mendoza@gmail.com,9.350306e+09,Region III,Central Luzon,Angeles,Brgy 9,2023-01-21,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,CUST000805,Maria,Fernandez,F,33.0,maria.fernandez49@outlook.com,9.755752e+09,Region VII,Central Visayas,Cebu City,Brgy 2,2023-02-27,Bronze
5046,CUST001442,Grace,Flores,F,41.0,graceflores@mailcom,9.253268e+09,Region III,Central Luzon,Angeles,Brgy 4,2025-11-27,Bronze
5047,CUST001095,Ana,Cruz,Unknown,25.0,ana.cruz@companymail.ph,9.218946e+09,Region IV-A,CALABARZON,San Pablo,Brgy 9,01/26/2025,Bronze
5048,CUST003989,Mia,Garcia,M,17.0,mia.garcia@mail.com,9.402610e+09,Region III,Central Luzon,San Fernando,Brgy 10,14-Oct-2024,Gold
5049,CUST003706,Faith,Fernandez,M,28.0,faith.fernandez@mail.com,NaN,CARAGA,Caraga,Butuan,Brgy 2,2024-01-29,Silver

In [160]:
customers_clean['gender'] = customers_clean['gender'].fillna("Unknown")

In [161]:
customers_clean.isna().sum().sort_values(ascending=False)

loyalty_tier    266
age             150
phone           147
email           107
customer_id       0
gender            0
last_name         0
first_name        0
region_code       0
region_name       0
city              0
barangay          0
signup_date       0
dtype: int64

In [162]:
customers_clean['age'] = customers_clean['age'].fillna(0)

In [163]:
customers_clean['phone'] = customers_clean['phone'].fillna('09100000001')

In [164]:
customers_clean['email'] = customers_clean['email'].fillna('email@gmail.com')

In [165]:
customers_clean['loyalty_tier'] = customers_clean['loyalty_tier'].fillna("Unknown")

In [166]:
returns_clean = data['returns'].copy()

In [167]:
returns_clean

,return_id,order_id,return_request_date,reason,refunded_flag,refund_amount
0,RET000001,ORD0008752,2025-01-09,Defective,No,NaN
1,RET000002,ORD0007359,2025-07-20,Wrong item,NaN,650.28
2,RET000003,ORD0009041,01/07/2025,Size issue,Yes,NaN
3,RET000004,ORD0000227,2025-03-04,Late delivery,Partial,NaN
4,RET000005,ORD0005754,2025-04-24,Size issue,Yes,713.39
...,...,...,...,...,...,...
1195,RET001196,ORD0008236,2024-11-02,Wrong item,Yes,1094.79
1196,RET001197,ORD0011974,10/10/2024,Late delivery,No,356.74
1197,RET001198,ORD0014526,2025-06-25,Size issue,Partial,500.08
1198,RET001199,ORD0011487,2024-02-20,Late delivery,No,171.28
1199,RET001200,ORD0013304,2025-08-12,Damaged item,Yes,857.96

In [168]:
returns_clean['refund_missing'] = returns_clean['refund_amount'].isna()

In [169]:
returns_clean

,return_id,order_id,return_request_date,reason,refunded_flag,refund_amount,refund_missing
0,RET000001,ORD0008752,2025-01-09,Defective,No,NaN,True
1,RET000002,ORD0007359,2025-07-20,Wrong item,NaN,650.28,False
2,RET000003,ORD0009041,01/07/2025,Size issue,Yes,NaN,True
3,RET000004,ORD0000227,2025-03-04,Late delivery,Partial,NaN,True
4,RET000005,ORD0005754,2025-04-24,Size issue,Yes,713.39,False
...,...,...,...,...,...,...,...
1195,RET001196,ORD0008236,2024-11-02,Wrong item,Yes,1094.79,False
1196,RET001197,ORD0011974,10/10/2024,Late delivery,No,356.74,False
1197,RET001198,ORD0014526,2025-06-25,Size issue,Partial,500.08,False
1198,RET001199,ORD0011487,2024-02-20,Late delivery,No,171.28,False
1199,RET001200,ORD0013304,2025-08-12,Damaged item,Yes,857.96,False

In [170]:
data['shipments']

,shipment_id,order_id,courier,tracking_no,shipment_status,ship_date,delivered_date
0,SHP0000001,ORD0000001,J&T,HLI2ORMO9V4O,Delivered,2025-09-05,09/06/2025
1,SHP0000002,ORD0000002,NinjaVan,E8XLRMV7QVEB,In Transit,2025-02-06,2025-02-12
2,SHP0000003,ORD0000003,2GO,LHLXVJF18MQB,Delivered,2025-07-23,2025-07-29
3,SHP0000004,ORD0000004,GrabExpress,RXUNTQ7WKL5B,Delivered,2025-01-21,2025-01-25
4,SHP0000005,ORD0000005,2GO,XQLUM80WBUSJ,In Transit,2025-09-21,2025-09-26
...,...,...,...,...,...,...,...
14995,SHP0014996,ORD0014996,NinjaVan,DSX72VVET6CL,Delivered,2024-02-21,2024-02-23
14996,SHP0014997,ORD0014997,GrabExpress,SVSYZ9YKBJYS,Delivered,2024-01-27,2024-02-03
14997,SHP0014998,ORD0014998,LBC,DVYT8KX7SF5I,Delivered,2025-01-25,2025-01-29
14998,SHP0014999,ORD0014999,J&T,X5P5PWP8DYU0,Delivered,2024-05-22,2024-05-26
14999,SHP0015000,ORD0015000,2GO,2VWTGJJS9XHI,Delivered,18-Jul-2025,07/19/2025

In [171]:
shipments_clean = data['shipments']

In [172]:
shipments_clean[shipments_clean["delivered_date"].isna()][
    ["shipment_id", "shipment_status", "ship_date", "delivered_date"]
]

      shipment_id shipment_status    ship_date delivered_date
24     SHP0000025       Delivered   2024-03-19            NaN
27     SHP0000028       Delivered   2024-03-31            NaN
38     SHP0000039       Delivered  13-Oct-2024            NaN
64     SHP0000065       Delivered   2024-01-19            NaN
71     SHP0000072       Delivered   2025-04-03            NaN
...           ...             ...          ...            ...
14916  SHP0014917       Delivered   2024-03-27            NaN
14958  SHP0014959       Delivered   2026-01-23            NaN
14978  SHP0014979       Delivered   2025-12-16            NaN
14981  SHP0014982      In Transit   2025-06-06            NaN
14994  SHP0014995      In Transit   2025-06-11            NaN

[729 rows x 4 columns]

In [173]:
age_analysis = data['customers'].dropna(subset=["age"]).copy

In [174]:
data['customers'].shape

(5050, 13)

In [176]:
age_analysis

<bound method NDFrame.copy of      customer_id first_name   last_name   gender   age  \
0     CUST000001      Grace  DelosReyes      NaN  20.0
1     CUST000002        Ana       Ramos   Female  35.0
2     CUST000003      Arvin     Navarro     Male  14.0
3     CUST000004       Kyle      Rivera        F  26.0
4     CUST000005       Juan     Mendoza     Male  29.0
...          ...        ...         ...      ...   ...
5045  CUST000805      Maria   Fernandez        F  33.0
5046  CUST001442      Grace      Flores        F  41.0
5047  CUST001095        Ana        Cruz  Unknown  25.0
5048  CUST003989        Mia      Garcia        M  17.0
5049  CUST003706      Faith   Fernandez        M  28.0

                               email         phone  region_code  \
0     grace.delosreyes95@outlook.com  9.196001e+09   Region III
1           ana.ramos@companymail.ph  9.026542e+09       CARAGA
2           arvin.navarrooutlook.com  9.161850e+09          NCR
3          kyle.rivera13@outlook.com  9.752553e+09   Region III
4             juan.mendoza@gmail.com  9.350306e+09   Region III
...                              ...           ...          ...
5045   maria.fernandez49@outlook.com  9.755752e+09   Region VII
5046             graceflores@mailcom  9.253268e+09   Region III
5047         ana.cruz@companymail.ph  9.218946e+09  Region IV-A
5048             mia.garcia@mail.com  9.402610e+09   Region III
5049        faith.fernandez@mail.com           NaN       CARAGA

          region_name          city barangay  signup_date loyalty_tier
0       Central Luzon       Angeles   Brgy 1   2025-12-31       Bronze
1              Caraga        Butuan   Brgy 9   2025-02-08       Bronze
2        Metro Manila         Pasig   Brgy 2   2023-09-10       Bronze
3       Central Luzon       Angeles   Brgy 1   2024-11-17          NaN
4       Central Luzon       Angeles   Brgy 9   2023-01-21         Gold
...               ...           ...      ...          ...          ...
5045  Central Visayas     Cebu City   Brgy 2   2023-02-27       Bronze
5046    Central Luzon       Angeles   Brgy 4   2025-11-27       Bronze
5047       CALABARZON     San Pablo   Brgy 9   01/26/2025       Bronze
5048    Central Luzon  San Fernando  Brgy 10  14-Oct-2024         Gold
5049           Caraga        Butuan   Brgy 2   2024-01-29       Silver

[4900 rows x 13 columns]>

In [177]:
customers_drop = data['customers'].dropna(subset=["age"])

In [178]:
customers_drop.shape

(4900, 13)

In [179]:
customers_drop.isna().sum()

customer_id       0
first_name        0
last_name         0
gender          290
age               0
email           106
phone           144
region_code       0
region_name       0
city              0
barangay          0
signup_date       0
loyalty_tier    256
dtype: int64

In [180]:
data['customers'].duplicated().sum()

np.int64(50)

In [181]:
data['orders'].duplicated().sum()

np.int64(75)

In [182]:
duplicated_orders = data['orders'][
    data['orders'].duplicated(subset=['order_id'], keep=False)
    ].sort_values('order_id')

In [183]:
duplicated_orders.head(10)

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee
648,ORD0000649,CUST001771,2025-11-08 20:35:00,Completed,Marketplace,Standard,0.183,135.68
15034,ORD0000649,CUST001771,2025-11-08 20:35:00,Completed,Marketplace,Standard,0.183,135.68
1082,ORD0001083,CUST003970,2024-01-13 12:25:00,Completed,Marketplace,Standard,0.086,34.51
15014,ORD0001083,CUST003970,2024-01-13 12:25:00,Completed,Marketplace,Standard,0.086,34.51
15038,ORD0001554,CUST004840,2024-10-02 19:57:00,Returned,Marketplace,Pickup,0.078,69.96
1553,ORD0001554,CUST004840,2024-10-02 19:57:00,Returned,Marketplace,Pickup,0.078,69.96
15027,ORD0001619,CUST001545,2024-11-01 03:26:00,Completed,Web,Standard,0.207,80.13
1618,ORD0001619,CUST001545,2024-11-01 03:26:00,Completed,Web,Standard,0.207,80.13
15035,ORD0001801,CUST004739,2025-05-03 18:11:00,Completed,Mobile App,Express,0.026,NaN
1800,ORD0001801,CUST004739,2025-05-03 18:11:00,Completed,Mobile App,Express,0.026,NaN

In [184]:
orders_clean = data['orders'].copy()

In [185]:
orders_clean.duplicated().sum()

np.int64(75)

In [186]:
orders_clean = data['orders'].drop_duplicates().copy()

In [187]:
orders_clean[orders_clean['order_id'] == "ORD0000649"]

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee
648,ORD0000649,CUST001771,2025-11-08 20:35:00,Completed,Marketplace,Standard,0.183,135.68

In [188]:
data['orders']['order_id'].is_unique

False

In [189]:
data['products']

,product_id,product_name,brand,category,unit_cost,unit_price,stock_qty,uom,launch_date
0,PROD00001,KidJoy Beauty 963,KidJoy,Beauty,44.17,64.5,125.0,pc,2022-01-18
1,PROD00002,HomeEase Home 368,HomeEase,Home and Kitchen,37.18,70.39,131.0,pcs,2022-11-25
2,PROD00003,FreshCart Fashion 911,FreshCart,Fashion,46.29,₱70.26,41.0,piece,2023-09-04
3,PROD00004,NovaTech Toys 753,NovaTech,Toys,43.66,62.46,149.0,pcs,2023-08-12
4,PROD00005,GlowCo Books 916,GlowCo,Books,64.59,82.02,162.0,bottle,2024-05-12
...,...,...,...,...,...,...,...,...,...
795,PROD00796,KidJoy Elec 294,KidJoy,Elec,83.80,132.12,111.0,bottle,2023-08-15
796,PROD00797,SunPeak Books 182,SunPeak,Books,53.67,62.54,163.0,bottle,2023-01-05
797,PROD00798,NovaTech Groceries 889,NovaTech,Groceries,63.54,112.46,155.0,set,2022-08-09
798,PROD00799,Acme Fashion 991,Acme,Fashion,25.27,34.96,169.0,bottle,2024-06-19
799,PROD00800,NovaTech Sports 419,NovaTech,Sports,70.14,116.39,245.0,piece,07/03/2022

In [190]:
def clean_currency(series):
    return pd.to_numeric(
        series.astype("string")
            .str.replace(
                "₱", "", regex=False)
            .str.replace(
                ",", "", regex=False)
            .str.strip(),
        errors="coerce"
    )

In [191]:
data['products']['unit_price_num'] = clean_currency(
    data['products']['unit_price']
)

In [192]:
data['products']

,product_id,product_name,brand,category,unit_cost,unit_price,stock_qty,uom,launch_date,unit_price_num
0,PROD00001,KidJoy Beauty 963,KidJoy,Beauty,44.17,64.5,125.0,pc,2022-01-18,64.5
1,PROD00002,HomeEase Home 368,HomeEase,Home and Kitchen,37.18,70.39,131.0,pcs,2022-11-25,70.39
2,PROD00003,FreshCart Fashion 911,FreshCart,Fashion,46.29,₱70.26,41.0,piece,2023-09-04,70.26
3,PROD00004,NovaTech Toys 753,NovaTech,Toys,43.66,62.46,149.0,pcs,2023-08-12,62.46
4,PROD00005,GlowCo Books 916,GlowCo,Books,64.59,82.02,162.0,bottle,2024-05-12,82.02
...,...,...,...,...,...,...,...,...,...,...
795,PROD00796,KidJoy Elec 294,KidJoy,Elec,83.80,132.12,111.0,bottle,2023-08-15,132.12
796,PROD00797,SunPeak Books 182,SunPeak,Books,53.67,62.54,163.0,bottle,2023-01-05,62.54
797,PROD00798,NovaTech Groceries 889,NovaTech,Groceries,63.54,112.46,155.0,set,2022-08-09,112.46
798,PROD00799,Acme Fashion 991,Acme,Fashion,25.27,34.96,169.0,bottle,2024-06-19,34.96
799,PROD00800,NovaTech Sports 419,NovaTech,Sports,70.14,116.39,245.0,piece,07/03/2022,116.39

In [193]:
data['products'] = data['products'].drop(columns='unit_price_num')

In [194]:
data['products']

,product_id,product_name,brand,category,unit_cost,unit_price,stock_qty,uom,launch_date
0,PROD00001,KidJoy Beauty 963,KidJoy,Beauty,44.17,64.5,125.0,pc,2022-01-18
1,PROD00002,HomeEase Home 368,HomeEase,Home and Kitchen,37.18,70.39,131.0,pcs,2022-11-25
2,PROD00003,FreshCart Fashion 911,FreshCart,Fashion,46.29,₱70.26,41.0,piece,2023-09-04
3,PROD00004,NovaTech Toys 753,NovaTech,Toys,43.66,62.46,149.0,pcs,2023-08-12
4,PROD00005,GlowCo Books 916,GlowCo,Books,64.59,82.02,162.0,bottle,2024-05-12
...,...,...,...,...,...,...,...,...,...
795,PROD00796,KidJoy Elec 294,KidJoy,Elec,83.80,132.12,111.0,bottle,2023-08-15
796,PROD00797,SunPeak Books 182,SunPeak,Books,53.67,62.54,163.0,bottle,2023-01-05
797,PROD00798,NovaTech Groceries 889,NovaTech,Groceries,63.54,112.46,155.0,set,2022-08-09
798,PROD00799,Acme Fashion 991,Acme,Fashion,25.27,34.96,169.0,bottle,2024-06-19
799,PROD00800,NovaTech Sports 419,NovaTech,Sports,70.14,116.39,245.0,piece,07/03/2022

In [195]:
data['products'] = data['products'].drop(columns='unit_price_num')

KeyError: "['unit_price_num'] not found in axis"

In [196]:
products_clean = data['products'].copy()

In [197]:
products_clean

,product_id,product_name,brand,category,unit_cost,unit_price,stock_qty,uom,launch_date
0,PROD00001,KidJoy Beauty 963,KidJoy,Beauty,44.17,64.5,125.0,pc,2022-01-18
1,PROD00002,HomeEase Home 368,HomeEase,Home and Kitchen,37.18,70.39,131.0,pcs,2022-11-25
2,PROD00003,FreshCart Fashion 911,FreshCart,Fashion,46.29,₱70.26,41.0,piece,2023-09-04
3,PROD00004,NovaTech Toys 753,NovaTech,Toys,43.66,62.46,149.0,pcs,2023-08-12
4,PROD00005,GlowCo Books 916,GlowCo,Books,64.59,82.02,162.0,bottle,2024-05-12
...,...,...,...,...,...,...,...,...,...
795,PROD00796,KidJoy Elec 294,KidJoy,Elec,83.80,132.12,111.0,bottle,2023-08-15
796,PROD00797,SunPeak Books 182,SunPeak,Books,53.67,62.54,163.0,bottle,2023-01-05
797,PROD00798,NovaTech Groceries 889,NovaTech,Groceries,63.54,112.46,155.0,set,2022-08-09
798,PROD00799,Acme Fashion 991,Acme,Fashion,25.27,34.96,169.0,bottle,2024-06-19
799,PROD00800,NovaTech Sports 419,NovaTech,Sports,70.14,116.39,245.0,piece,07/03/2022

In [198]:
customers_clean

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier
0,CUST000001,Grace,DelosReyes,Unknown,20.0,grace.delosreyes95@outlook.com,9196001338.0,Region III,Central Luzon,Angeles,Brgy 1,2025-12-31,Bronze
1,CUST000002,Ana,Ramos,Female,35.0,ana.ramos@companymail.ph,9026542351.0,CARAGA,Caraga,Butuan,Brgy 9,2025-02-08,Bronze
2,CUST000003,Arvin,Navarro,Male,14.0,arvin.navarrooutlook.com,9161849593.0,NCR,Metro Manila,Pasig,Brgy 2,2023-09-10,Bronze
3,CUST000004,Kyle,Rivera,F,26.0,kyle.rivera13@outlook.com,9752553419.0,Region III,Central Luzon,Angeles,Brgy 1,2024-11-17,Unknown
4,CUST000005,Juan,Mendoza,Male,29.0,juan.mendoza@gmail.com,9350305641.0,Region III,Central Luzon,Angeles,Brgy 9,2023-01-21,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,CUST000805,Maria,Fernandez,F,33.0,maria.fernandez49@outlook.com,9755752250.0,Region VII,Central Visayas,Cebu City,Brgy 2,2023-02-27,Bronze
5046,CUST001442,Grace,Flores,F,41.0,graceflores@mailcom,9253267699.0,Region III,Central Luzon,Angeles,Brgy 4,2025-11-27,Bronze
5047,CUST001095,Ana,Cruz,Unknown,25.0,ana.cruz@companymail.ph,9218945590.0,Region IV-A,CALABARZON,San Pablo,Brgy 9,01/26/2025,Bronze
5048,CUST003989,Mia,Garcia,M,17.0,mia.garcia@mail.com,9402610158.0,Region III,Central Luzon,San Fernando,Brgy 10,14-Oct-2024,Gold
5049,CUST003706,Faith,Fernandez,M,28.0,faith.fernandez@mail.com,09100000001,CARAGA,Caraga,Butuan,Brgy 2,2024-01-29,Silver

In [199]:
customers_clean['gender']

0       Unknown
1        Female
2          Male
3             F
4          Male
         ...
5045          F
5046          F
5047    Unknown
5048          M
5049          M
Name: gender, Length: 5050, dtype: str

In [200]:
customers_clean["gender_clean"] = (
    customers_clean["gender"]
        .astype("string")
        .str.strip()
        .str.lower()
        .replace({
            "m": "Male",
            "male": "Male",
            "M": "Male",
            "f": "Female",
            "F": "Female",
            "female": "Female",
            "unknown": "Unknown"
        })
        .fillna("Unknown")
)

In [201]:
customers_clean

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier,gender_clean
0,CUST000001,Grace,DelosReyes,Unknown,20.0,grace.delosreyes95@outlook.com,9196001338.0,Region III,Central Luzon,Angeles,Brgy 1,2025-12-31,Bronze,Unknown
1,CUST000002,Ana,Ramos,Female,35.0,ana.ramos@companymail.ph,9026542351.0,CARAGA,Caraga,Butuan,Brgy 9,2025-02-08,Bronze,Female
2,CUST000003,Arvin,Navarro,Male,14.0,arvin.navarrooutlook.com,9161849593.0,NCR,Metro Manila,Pasig,Brgy 2,2023-09-10,Bronze,Male
3,CUST000004,Kyle,Rivera,F,26.0,kyle.rivera13@outlook.com,9752553419.0,Region III,Central Luzon,Angeles,Brgy 1,2024-11-17,Unknown,Female
4,CUST000005,Juan,Mendoza,Male,29.0,juan.mendoza@gmail.com,9350305641.0,Region III,Central Luzon,Angeles,Brgy 9,2023-01-21,Gold,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,CUST000805,Maria,Fernandez,F,33.0,maria.fernandez49@outlook.com,9755752250.0,Region VII,Central Visayas,Cebu City,Brgy 2,2023-02-27,Bronze,Female
5046,CUST001442,Grace,Flores,F,41.0,graceflores@mailcom,9253267699.0,Region III,Central Luzon,Angeles,Brgy 4,2025-11-27,Bronze,Female
5047,CUST001095,Ana,Cruz,Unknown,25.0,ana.cruz@companymail.ph,9218945590.0,Region IV-A,CALABARZON,San Pablo,Brgy 9,01/26/2025,Bronze,Unknown
5048,CUST003989,Mia,Garcia,M,17.0,mia.garcia@mail.com,9402610158.0,Region III,Central Luzon,San Fernando,Brgy 10,14-Oct-2024,Gold,Male
5049,CUST003706,Faith,Fernandez,M,28.0,faith.fernandez@mail.com,09100000001,CARAGA,Caraga,Butuan,Brgy 2,2024-01-29,Silver,Male

In [202]:
products_clean = data['products'].copy()

In [203]:
category_base = (
    products_clean['category']
    .astype('string')
    .str.strip()
    .str.lower()
)

In [204]:
category_map = {
    "electronics": "Electronics",
    "elec": "Electronics",
    "book": "Books",
    "books": "Books",
    "grocery": "Groceries",
    "groceries": "Groceries",
    "home and kitchen": "Home & Kitchen",
    "home & kitchen": "Home & Kitchen",
    "toy": "Toys",
    "toys": "Toys",
    "beauty & care": "Beauty",
    "beauty": "Beauty",
    "fashon": "Fashion",
    "fashion": "Fashion",
    "sports & outdoor": "Sports",
    "sports": "Sports"
}

In [205]:
products_clean['category_clean'] = category_base.replace(category_map)

In [206]:
products_clean['category'].value_counts()

category
Beauty              94
Toys                92
Books               90
Fashion             89
Groceries           77
Home & Kitchen      76
Sports              74
Electronics         71
electronics         20
Book                20
Home and Kitchen    19
Electronics         17
Grocery             12
Elec                11
Beauty & Care       11
Toy                 11
Fashon               8
Sports & Outdoor     8
Name: count, dtype: int64

In [207]:
orders_clean['order_datetime_clean'] = pd.to_datetime(
    orders_clean['order_datetime'],
    format='mixed',
    errors='coerce'
)

In [208]:
orders_clean

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee,order_datetime_clean
0,ORD0000001,CUST000839,2025-11-07 17:02:00,Cancelled,Marketplace,Standard,0.074,102.68,2025-11-07 17:02:00
1,ORD0000002,CUST002871,09/18/2025 09:13 AM,Completed,Marketplace,Express,0.063,0.00,2025-09-18 09:13:00
2,ORD0000003,CUST000720,2025-08-08 04:59:00,Completed,Web,Standard,0.137,103.83,2025-08-08 04:59:00
3,ORD0000004,CUST002515,2025-10-14 12:56:00,Completed,Web,Pickup,0.005,112.69,2025-10-14 12:56:00
4,ORD0000005,CUST001544,2024-05-30 04:56:00,Completed,Marketplace,Pickup,NaN,111.73,2024-05-30 04:56:00
...,...,...,...,...,...,...,...,...,...
14995,ORD0014996,CUST003231,2025-02-24 15:40:00,Completed,Web,Pickup,0.001,47.33,2025-02-24 15:40:00
14996,ORD0014997,CUST002061,2024-10-05 12:20:00,Completed,Web,Standard,0.078,73.77,2024-10-05 12:20:00
14997,ORD0014998,CUST000852,2026-01-23 00:19:00,Pending,Marketplace,Standard,0.031,81.18,2026-01-23 00:19:00
14998,ORD0014999,CUST002641,2024-08-26 00:48:00,Shipped,Web,Pickup,0.184,101.35,2024-08-26 00:48:00
14999,ORD0015000,CUST002567,2025-07-23 09:55:00,Completed,Marketplace,Pickup,0.104,67.03,2025-07-23 09:55:00

In [209]:
orders_clean.dtypes

order_id                           str
customer_id                        str
order_datetime                     str
order_status                       str
sales_channel                      str
shipping_method                    str
discount_pct                   float64
shipping_fee                   float64
order_datetime_clean    datetime64[us]
dtype: object

In [210]:
shipments_clean = data['shipments']

In [211]:
shipments_clean

,shipment_id,order_id,courier,tracking_no,shipment_status,ship_date,delivered_date
0,SHP0000001,ORD0000001,J&T,HLI2ORMO9V4O,Delivered,2025-09-05,09/06/2025
1,SHP0000002,ORD0000002,NinjaVan,E8XLRMV7QVEB,In Transit,2025-02-06,2025-02-12
2,SHP0000003,ORD0000003,2GO,LHLXVJF18MQB,Delivered,2025-07-23,2025-07-29
3,SHP0000004,ORD0000004,GrabExpress,RXUNTQ7WKL5B,Delivered,2025-01-21,2025-01-25
4,SHP0000005,ORD0000005,2GO,XQLUM80WBUSJ,In Transit,2025-09-21,2025-09-26
...,...,...,...,...,...,...,...
14995,SHP0014996,ORD0014996,NinjaVan,DSX72VVET6CL,Delivered,2024-02-21,2024-02-23
14996,SHP0014997,ORD0014997,GrabExpress,SVSYZ9YKBJYS,Delivered,2024-01-27,2024-02-03
14997,SHP0014998,ORD0014998,LBC,DVYT8KX7SF5I,Delivered,2025-01-25,2025-01-29
14998,SHP0014999,ORD0014999,J&T,X5P5PWP8DYU0,Delivered,2024-05-22,2024-05-26
14999,SHP0015000,ORD0015000,2GO,2VWTGJJS9XHI,Delivered,18-Jul-2025,07/19/2025

In [212]:
shipments_clean['ship_date_clean'] = pd.to_datetime(
    shipments_clean['ship_date'],
    format='mixed',
    errors='coerce'
)

In [213]:
shipments_clean['delivered_date_clean'] = pd.to_datetime(
    shipments_clean['delivered_date'],
    format='mixed',
    errors='coerce'
)

In [214]:
shipments_clean

,shipment_id,order_id,courier,tracking_no,shipment_status,ship_date,delivered_date,ship_date_clean,delivered_date_clean
0,SHP0000001,ORD0000001,J&T,HLI2ORMO9V4O,Delivered,2025-09-05,09/06/2025,2025-09-05,2025-09-06
1,SHP0000002,ORD0000002,NinjaVan,E8XLRMV7QVEB,In Transit,2025-02-06,2025-02-12,2025-02-06,2025-02-12
2,SHP0000003,ORD0000003,2GO,LHLXVJF18MQB,Delivered,2025-07-23,2025-07-29,2025-07-23,2025-07-29
3,SHP0000004,ORD0000004,GrabExpress,RXUNTQ7WKL5B,Delivered,2025-01-21,2025-01-25,2025-01-21,2025-01-25
4,SHP0000005,ORD0000005,2GO,XQLUM80WBUSJ,In Transit,2025-09-21,2025-09-26,2025-09-21,2025-09-26
...,...,...,...,...,...,...,...,...,...
14995,SHP0014996,ORD0014996,NinjaVan,DSX72VVET6CL,Delivered,2024-02-21,2024-02-23,2024-02-21,2024-02-23
14996,SHP0014997,ORD0014997,GrabExpress,SVSYZ9YKBJYS,Delivered,2024-01-27,2024-02-03,2024-01-27,2024-02-03
14997,SHP0014998,ORD0014998,LBC,DVYT8KX7SF5I,Delivered,2025-01-25,2025-01-29,2025-01-25,2025-01-29
14998,SHP0014999,ORD0014999,J&T,X5P5PWP8DYU0,Delivered,2024-05-22,2024-05-26,2024-05-22,2024-05-26
14999,SHP0015000,ORD0015000,2GO,2VWTGJJS9XHI,Delivered,18-Jul-2025,07/19/2025,2025-07-18,2025-07-19

In [215]:
#calculate delivery duration

shipments_clean['delivery_days'] = (
    shipments_clean['delivered_date_clean'] - shipments_clean['ship_date_clean']
).dt.days

In [216]:
shipments_clean['delivery_days'].describe()

count    14271.000000
mean         3.997968
std          1.991026
min          1.000000
25%          2.000000
50%          4.000000
75%          6.000000
max          7.000000
Name: delivery_days, dtype: float64

In [217]:
shipments_clean

,shipment_id,order_id,courier,tracking_no,shipment_status,ship_date,delivered_date,ship_date_clean,delivered_date_clean,delivery_days
0,SHP0000001,ORD0000001,J&T,HLI2ORMO9V4O,Delivered,2025-09-05,09/06/2025,2025-09-05,2025-09-06,1.0
1,SHP0000002,ORD0000002,NinjaVan,E8XLRMV7QVEB,In Transit,2025-02-06,2025-02-12,2025-02-06,2025-02-12,6.0
2,SHP0000003,ORD0000003,2GO,LHLXVJF18MQB,Delivered,2025-07-23,2025-07-29,2025-07-23,2025-07-29,6.0
3,SHP0000004,ORD0000004,GrabExpress,RXUNTQ7WKL5B,Delivered,2025-01-21,2025-01-25,2025-01-21,2025-01-25,4.0
4,SHP0000005,ORD0000005,2GO,XQLUM80WBUSJ,In Transit,2025-09-21,2025-09-26,2025-09-21,2025-09-26,5.0
...,...,...,...,...,...,...,...,...,...,...
14995,SHP0014996,ORD0014996,NinjaVan,DSX72VVET6CL,Delivered,2024-02-21,2024-02-23,2024-02-21,2024-02-23,2.0
14996,SHP0014997,ORD0014997,GrabExpress,SVSYZ9YKBJYS,Delivered,2024-01-27,2024-02-03,2024-01-27,2024-02-03,7.0
14997,SHP0014998,ORD0014998,LBC,DVYT8KX7SF5I,Delivered,2025-01-25,2025-01-29,2025-01-25,2025-01-29,4.0
14998,SHP0014999,ORD0014999,J&T,X5P5PWP8DYU0,Delivered,2024-05-22,2024-05-26,2024-05-22,2024-05-26,4.0
14999,SHP0015000,ORD0015000,2GO,2VWTGJJS9XHI,Delivered,18-Jul-2025,07/19/2025,2025-07-18,2025-07-19,1.0

In [218]:
orders_clean

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee,order_datetime_clean
0,ORD0000001,CUST000839,2025-11-07 17:02:00,Cancelled,Marketplace,Standard,0.074,102.68,2025-11-07 17:02:00
1,ORD0000002,CUST002871,09/18/2025 09:13 AM,Completed,Marketplace,Express,0.063,0.00,2025-09-18 09:13:00
2,ORD0000003,CUST000720,2025-08-08 04:59:00,Completed,Web,Standard,0.137,103.83,2025-08-08 04:59:00
3,ORD0000004,CUST002515,2025-10-14 12:56:00,Completed,Web,Pickup,0.005,112.69,2025-10-14 12:56:00
4,ORD0000005,CUST001544,2024-05-30 04:56:00,Completed,Marketplace,Pickup,NaN,111.73,2024-05-30 04:56:00
...,...,...,...,...,...,...,...,...,...
14995,ORD0014996,CUST003231,2025-02-24 15:40:00,Completed,Web,Pickup,0.001,47.33,2025-02-24 15:40:00
14996,ORD0014997,CUST002061,2024-10-05 12:20:00,Completed,Web,Standard,0.078,73.77,2024-10-05 12:20:00
14997,ORD0014998,CUST000852,2026-01-23 00:19:00,Pending,Marketplace,Standard,0.031,81.18,2026-01-23 00:19:00
14998,ORD0014999,CUST002641,2024-08-26 00:48:00,Shipped,Web,Pickup,0.184,101.35,2024-08-26 00:48:00
14999,ORD0015000,CUST002567,2025-07-23 09:55:00,Completed,Marketplace,Pickup,0.104,67.03,2025-07-23 09:55:00

In [219]:
orders_clean['order_month'] = (
    orders_clean['order_datetime_clean'].dt.to_period("M")
)

In [220]:
orders_clean

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee,order_datetime_clean,order_month
0,ORD0000001,CUST000839,2025-11-07 17:02:00,Cancelled,Marketplace,Standard,0.074,102.68,2025-11-07 17:02:00,2025-11
1,ORD0000002,CUST002871,09/18/2025 09:13 AM,Completed,Marketplace,Express,0.063,0.00,2025-09-18 09:13:00,2025-09
2,ORD0000003,CUST000720,2025-08-08 04:59:00,Completed,Web,Standard,0.137,103.83,2025-08-08 04:59:00,2025-08
3,ORD0000004,CUST002515,2025-10-14 12:56:00,Completed,Web,Pickup,0.005,112.69,2025-10-14 12:56:00,2025-10
4,ORD0000005,CUST001544,2024-05-30 04:56:00,Completed,Marketplace,Pickup,NaN,111.73,2024-05-30 04:56:00,2024-05
...,...,...,...,...,...,...,...,...,...,...
14995,ORD0014996,CUST003231,2025-02-24 15:40:00,Completed,Web,Pickup,0.001,47.33,2025-02-24 15:40:00,2025-02
14996,ORD0014997,CUST002061,2024-10-05 12:20:00,Completed,Web,Standard,0.078,73.77,2024-10-05 12:20:00,2024-10
14997,ORD0014998,CUST000852,2026-01-23 00:19:00,Pending,Marketplace,Standard,0.031,81.18,2026-01-23 00:19:00,2026-01
14998,ORD0014999,CUST002641,2024-08-26 00:48:00,Shipped,Web,Pickup,0.184,101.35,2024-08-26 00:48:00,2024-08
14999,ORD0015000,CUST002567,2025-07-23 09:55:00,Completed,Marketplace,Pickup,0.104,67.03,2025-07-23 09:55:00,2025-07

In [221]:
negative_age = customers_clean['age'] < 0

In [222]:
negative_age.sum()

np.int64(49)

In [223]:
customers_clean.loc[negative_age, ['customer_id','age']].head()

    customer_id  age
162  CUST000163 -1.0
329  CUST000330 -1.0
696  CUST000697 -1.0
718  CUST000719 -1.0
872  CUST000873 -1.0

In [224]:
under_18 = customers_clean['age'].between(0,17)

In [225]:
under_18.sum()

np.int64(569)

In [226]:
zero_qty = customers_clean['age'] <= 0

In [227]:
zero_qty.sum()

np.int64(200)

In [228]:
customers_clean

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier,gender_clean
0,CUST000001,Grace,DelosReyes,Unknown,20.0,grace.delosreyes95@outlook.com,9196001338.0,Region III,Central Luzon,Angeles,Brgy 1,2025-12-31,Bronze,Unknown
1,CUST000002,Ana,Ramos,Female,35.0,ana.ramos@companymail.ph,9026542351.0,CARAGA,Caraga,Butuan,Brgy 9,2025-02-08,Bronze,Female
2,CUST000003,Arvin,Navarro,Male,14.0,arvin.navarrooutlook.com,9161849593.0,NCR,Metro Manila,Pasig,Brgy 2,2023-09-10,Bronze,Male
3,CUST000004,Kyle,Rivera,F,26.0,kyle.rivera13@outlook.com,9752553419.0,Region III,Central Luzon,Angeles,Brgy 1,2024-11-17,Unknown,Female
4,CUST000005,Juan,Mendoza,Male,29.0,juan.mendoza@gmail.com,9350305641.0,Region III,Central Luzon,Angeles,Brgy 9,2023-01-21,Gold,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,CUST000805,Maria,Fernandez,F,33.0,maria.fernandez49@outlook.com,9755752250.0,Region VII,Central Visayas,Cebu City,Brgy 2,2023-02-27,Bronze,Female
5046,CUST001442,Grace,Flores,F,41.0,graceflores@mailcom,9253267699.0,Region III,Central Luzon,Angeles,Brgy 4,2025-11-27,Bronze,Female
5047,CUST001095,Ana,Cruz,Unknown,25.0,ana.cruz@companymail.ph,9218945590.0,Region IV-A,CALABARZON,San Pablo,Brgy 9,01/26/2025,Bronze,Unknown
5048,CUST003989,Mia,Garcia,M,17.0,mia.garcia@mail.com,9402610158.0,Region III,Central Luzon,San Fernando,Brgy 10,14-Oct-2024,Gold,Male
5049,CUST003706,Faith,Fernandez,M,28.0,faith.fernandez@mail.com,09100000001,CARAGA,Caraga,Butuan,Brgy 2,2024-01-29,Silver,Male

In [229]:
invalid_age = negative_age | under_18 | zero_qty

In [230]:
customers_clean.loc[invalid_age,  'age_clean'] = np.nan

In [231]:
customers_clean

,customer_id,first_name,last_name,gender,age,email,phone,region_code,region_name,city,barangay,signup_date,loyalty_tier,gender_clean,age_clean
0,CUST000001,Grace,DelosReyes,Unknown,20.0,grace.delosreyes95@outlook.com,9196001338.0,Region III,Central Luzon,Angeles,Brgy 1,2025-12-31,Bronze,Unknown,NaN
1,CUST000002,Ana,Ramos,Female,35.0,ana.ramos@companymail.ph,9026542351.0,CARAGA,Caraga,Butuan,Brgy 9,2025-02-08,Bronze,Female,NaN
2,CUST000003,Arvin,Navarro,Male,14.0,arvin.navarrooutlook.com,9161849593.0,NCR,Metro Manila,Pasig,Brgy 2,2023-09-10,Bronze,Male,NaN
3,CUST000004,Kyle,Rivera,F,26.0,kyle.rivera13@outlook.com,9752553419.0,Region III,Central Luzon,Angeles,Brgy 1,2024-11-17,Unknown,Female,NaN
4,CUST000005,Juan,Mendoza,Male,29.0,juan.mendoza@gmail.com,9350305641.0,Region III,Central Luzon,Angeles,Brgy 9,2023-01-21,Gold,Male,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,CUST000805,Maria,Fernandez,F,33.0,maria.fernandez49@outlook.com,9755752250.0,Region VII,Central Visayas,Cebu City,Brgy 2,2023-02-27,Bronze,Female,NaN
5046,CUST001442,Grace,Flores,F,41.0,graceflores@mailcom,9253267699.0,Region III,Central Luzon,Angeles,Brgy 4,2025-11-27,Bronze,Female,NaN
5047,CUST001095,Ana,Cruz,Unknown,25.0,ana.cruz@companymail.ph,9218945590.0,Region IV-A,CALABARZON,San Pablo,Brgy 9,01/26/2025,Bronze,Unknown,NaN
5048,CUST003989,Mia,Garcia,M,17.0,mia.garcia@mail.com,9402610158.0,Region III,Central Luzon,San Fernando,Brgy 10,14-Oct-2024,Gold,Male,NaN
5049,CUST003706,Faith,Fernandez,M,28.0,faith.fernandez@mail.com,09100000001,CARAGA,Caraga,Butuan,Brgy 2,2024-01-29,Silver,Male,NaN

In [232]:
missing_customers =(
    set(orders_clean['customer_id']) - set(customers_clean['customer_id'])
)

In [233]:
missing_customers

{'CUST999999'}

In [234]:
orphan_orders_rows = orders_clean[
    ~orders_clean['customer_id'].isin(customers_clean['customer_id'])
]

#~ means not found

In [235]:
orphan_orders_rows.info()

<class 'pandas.DataFrame'>
Index: 43 entries, 602 to 14450
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              43 non-null     str
 1   customer_id           43 non-null     str
 2   order_datetime        43 non-null     str
 3   order_status          43 non-null     str
 4   sales_channel         43 non-null     str
 5   shipping_method       43 non-null     str
 6   discount_pct          40 non-null     float64
 7   shipping_fee          43 non-null     float64
 8   order_datetime_clean  43 non-null     datetime64[us]
 9   order_month           43 non-null     period[M]
dtypes: datetime64[us](1), float64(2), period[M](1), str(6)
memory usage: 3.7 KB

In [236]:
orphan_orders_rows

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee,order_datetime_clean,order_month
602,ORD0000603,CUST999999,01/02/2024 09:07 PM,Shipped,Web,Express,0.101,100.45,2024-01-02 21:07:00,2024-01
756,ORD0000757,CUST999999,2025-05-19 14:53:00,Completed,Web,Standard,0.005,71.00,2025-05-19 14:53:00,2025-05
806,ORD0000807,CUST999999,2024-04-06 03:40:00,Completed,Web,Standard,0.194,94.34,2024-04-06 03:40:00,2024-04
1478,ORD0001479,CUST999999,2024-04-02 23:15:00,Completed,Mobile App,Express,0.161,107.78,2024-04-02 23:15:00,2024-04
1855,ORD0001856,CUST999999,2024-08-08 01:40:00,Completed,Mobile App,Express,0.080,101.14,2024-08-08 01:40:00,2024-08
2770,ORD0002771,CUST999999,2025-01-28 12:40:00,Completed,Mobile App,Pickup,0.091,100.96,2025-01-28 12:40:00,2025-01
2919,ORD0002920,CUST999999,2024-10-21 09:50:00,Completed,Marketplace,Pickup,0.067,74.64,2024-10-21 09:50:00,2024-10
3569,ORD0003570,CUST999999,06/05/2024 09:24 AM,Cancelled,Web,Express,0.029,104.07,2024-06-05 09:24:00,2024-06
3760,ORD0003761,CUST999999,2025-11-20 20:33:00,Returned,Marketplace,Pickup,0.000,94.26,2025-11-20 20:33:00,2025-11
4881,ORD0004882,CUST999999,2025-05-16 16:56:00,Completed,Mobile App,Express,0.000,64.93,2025-05-16 16:56:00,2025-05
4887,ORD0004888,CUST999999,10/15/2025 07:31 AM,Completed,Web,Pickup,0.000,122.26,2025-10-15 07:31:00,2025-10
4891,ORD0004892,CUST999999,2024-05-07 17:14:00,Pending,Mobile App,Express,0.114,62.66,2024-05-07 17:14:00,2024-05
5064,ORD0005065,CUST999999,2026-01-17 05:27:00,Completed,Marketplace,Pickup,0.000,85.11,2026-01-17 05:27:00,2026-01
5128,ORD0005129,CUST999999,03/29/2024 12:39 PM,Completed,Mobile App,Standard,NaN,37.05,2024-03-29 12:39:00,2024-03
5292,ORD0005293,CUST999999,2025-10-16 20:56:00,Completed,Marketplace,Pickup,0.302,49.99,2025-10-16 20:56:00,2025-10
5402,ORD0005403,CUST999999,2024-06-25 12:32:00,Completed,Mobile App,Standard,0.000,151.33,2024-06-25 12:32:00,2024-06
5674,ORD0005675,CUST999999,09/09/2025 10:48 PM,Completed,Marketplace,Pickup,NaN,70.47,2025-09-09 22:48:00,2025-09
5898,ORD0005899,CUST999999,2026-01-01 10:01:00,Cancelled,Marketplace,Express,0.140,5.59,2026-01-01 10:01:00,2026-01
6121,ORD0006122,CUST999999,03/03/2024 10:54 PM,Pending,Marketplace,Standard,0.080,111.26,2024-03-03 22:54:00,2024-03
6125,ORD0006126,CUST999999,2024-08-05 03:11:00,Completed,Mobile App,Standard,0.000,92.05,2024-08-05 03:11:00,2024-08
6272,ORD0006273,CUST999999,2025-06-03 19:59:00,Completed,Web,Standard,0.046,57.76,2025-06-03 19:59:00,2025-06
6833,ORD0006834,CUST999999,2024-05-17 20:59:00,Completed,Marketplace,Pickup,0.075,61.71,2024-05-17 20:59:00,2024-05
6886,ORD0006887,CUST999999,2025-02-23 19:26:00,Completed,Mobile App,Standard,0.039,59.69,2025-02-23 19:26:00,2025-02
7295,ORD0007296,CUST999999,2024-05-31 16:42:00,Pending,Web,Standard,0.156,37.85,2024-05-31 16:42:00,2024-05
7720,ORD0007721,CUST999999,06/05/2025 07:16 AM,Completed,Web,Pickup,0.089,95.38,2025-06-05 07:16:00,2025-06
7721,ORD0007722,CUST999999,2024-03-06 14:18:00,Completed,Web,Standard,0.071,134.71,2024-03-06 14:18:00,2024-03
8155,ORD0008156,CUST999999,2025-08-18 08:45:00,Completed,Web,Pickup,0.180,11.76,2025-08-18 08:45:00,2025-08
8237,ORD0008238,CUST999999,07/12/2024 09:03 PM,Completed,Mobile App,Standard,0.014,61.38,2024-07-12 21:03:00,2024-07
8313,ORD0008314,CUST999999,2024-07-21 18:26:00,Completed,Marketplace,Express,0.105,88.69,2024-07-21 18:26:00,2024-07
8580,ORD0008581,CUST999999,11/12/2025 12:34 AM,Completed,Mobile App,Standard,0.000,87.17,2025-11-12 00:34:00,2025-11
9338,ORD0009339,CUST999999,03/12/2024 02:23 PM,Cancelled,Mobile App,Pickup,0.076,70.38,2024-03-12 14:23:00,2024-03
9533,ORD0009534,CUST999999,16-Apr-2024 22:51,Completed,Marketplace,Pickup,0.000,99.03,2024-04-16 22:51:00,2024-04
10284,ORD0010285,CUST999999,27-Feb-2025 02:46,Cancelled,Web,Standard,0.074,165.93,2025-02-27 02:46:00,2025-02
10365,ORD0010366,CUST999999,2024-05-05 02:10:00,Completed,Mobile App,Pickup,0.229,93.97,2024-05-05 02:10:00,2024-05
10457,ORD0010458,CUST999999,2024-06-29 10:36:00,Completed,Marketplace,Standard,0.000,112.26,2024-06-29 10:36:00,2024-06
10675,ORD0010676,CUST999999,2025-02-28 12:31:00,Pending,Web,Express,0.076,89.33,2025-02-28 12:31:00,2025-02
10791,ORD0010792,CUST999999,2024-04-11 16:04:00,Completed,Marketplace,Express,0.169,59.91,2024-04-11 16:04:00,2024-04
11224,ORD0011225,CUST999999,04/24/2024 04:52 PM,Completed,Mobile App,Express,NaN,120.16,2024-04-24 16:52:00,2024-04
12257,ORD0012258,CUST999999,2024-07-09 18:38:00,Completed,Mobile App,Express,0.066,116.58,2024-07-09 18:38:00,2024-07
12901,ORD0012902,CUST999999,2024-01-27 17:20:00,Completed,Web,Express,0.054,106.20,2024-01-27 17:20:00,2024-01
13188,ORD0013189,CUST999999,26-Jan-2026 08:37,Returned,Marketplace,Express,0.162,88.99,2026-01-26 08:37:00,2026-01
14196,ORD0014197,CUST999999,09-Jan-2024 16:47,Completed,Mobile App,Express,0.127,40.38,2024-01-09 16:47:00,2024-01
14450,ORD0014451,CUST999999,01/05/2025 08:55 AM,Completed,Marketplace,Express,0.003,2.08,2025-01-05 08:55:00,2025-01

In [237]:
items_clean = data['order_items'].drop_duplicates().copy()

In [238]:
missing_products = (
    set(items_clean['product_id']) - set(data['products']['product_id'])
)

In [239]:
missing_products

{'PROD00000'}

In [240]:
orpan_product_rows = items_clean[
    ~items_clean['product_id'].isin(data['products']['product_id'])
]

In [241]:
orpan_product_rows

       order_item_id    order_id product_id  quantity unit_price_at_purchase
377    ITEM000000378  ORD0000148  PROD00000         1                  106.4
601    ITEM000000602  ORD0000241  PROD00000         1                  54.41
692    ITEM000000693  ORD0000275  PROD00000         2                 135.29
935    ITEM000000936  ORD0000370  PROD00000         1                  30.34
1108   ITEM000001109  ORD0000435  PROD00000         1                  95.17
...              ...         ...        ...       ...                    ...
37231  ITEM000037232  ORD0014893  PROD00000         3                 161.46
37339  ITEM000037340  ORD0014935  PROD00000         6                  188.5
37373  ITEM000037374  ORD0014952  PROD00000         1                 137.74
37464  ITEM000037465  ORD0014986  PROD00000         4                  58.28
37496  ITEM000037497  ORD0014999  PROD00000         1                  63.45

[129 rows x 5 columns]

In [242]:
audit = items_clean.merge(
    data['products'][['product_id','product_name']],
    on='product_id',
    how='left',
    indicator=True
)

In [243]:
audit['_merge'].value_counts()

_merge
both          37372
left_only       129
right_only        0
Name: count, dtype: int64

In [244]:
audit

,order_item_id,order_id,product_id,quantity,unit_price_at_purchase,product_name,_merge
0,ITEM000000001,ORD0000001,PROD00513,2,120.67,HomeEase Sports 313,both
1,ITEM000000002,ORD0000002,PROD00124,2,83.58,NovaTech Beauty 892,both
2,ITEM000000003,ORD0000002,PROD00631,2,46.96,BookNest Electronics 252,both
3,ITEM000000004,ORD0000002,PROD00136,1,100.59,GlowCo Groceries 689,both
4,ITEM000000005,ORD0000002,PROD00090,1,109.18,BookNest Home 591,both
...,...,...,...,...,...,...,...
37496,ITEM000037497,ORD0014999,PROD00000,1,63.45,NaN,left_only
37497,ITEM000037498,ORD0014999,PROD00138,1,128.96,KidJoy Toys 976,both
37498,ITEM000037499,ORD0014999,PROD00689,3,NaN,FreshCart Sports 375,both
37499,ITEM000037500,ORD0015000,PROD00376,2,208.44,KidJoy Beauty 728,both
37500,ITEM000037501,ORD0015000,PROD00584,2,63.2,HomeEase Electronics 592,both

In [248]:
items_analysis = items_clean.copy()

items_analysis["purchase_price_num"] = (
    clean_currency(
        items_analysis["unit_price_at_purchase"]
    )
)

items_analysis = items_analysis[
    (items_analysis["quantity"] > 0)
    & items_analysis["purchase_price_num"].notna()
]

items_analysis = items_analysis.merge(
    products_clean[["product_id", "unit_cost",
              "category_clean"]],
    on="product_id", how="left"
)

items_analysis["line_revenue"] = (
    items_analysis["quantity"]
    * items_analysis["purchase_price_num"]
)

items_analysis["line_cost"] = (
    items_analysis["quantity"]
    * items_analysis["unit_cost"]
)

In [250]:
items_clean

       order_item_id    order_id product_id  quantity unit_price_at_purchase
0      ITEM000000001  ORD0000001  PROD00513         2                 120.67
1      ITEM000000002  ORD0000002  PROD00124         2                  83.58
2      ITEM000000003  ORD0000002  PROD00631         2                  46.96
3      ITEM000000004  ORD0000002  PROD00136         1                 100.59
4      ITEM000000005  ORD0000002  PROD00090         1                 109.18
...              ...         ...        ...       ...                    ...
37496  ITEM000037497  ORD0014999  PROD00000         1                  63.45
37497  ITEM000037498  ORD0014999  PROD00138         1                 128.96
37498  ITEM000037499  ORD0014999  PROD00689         3                    NaN
37499  ITEM000037500  ORD0015000  PROD00376         2                 208.44
37500  ITEM000037501  ORD0015000  PROD00584         2                   63.2

[37501 rows x 5 columns]

In [262]:
sales_analysis = items_analysis.merge(
    orders_clean[[
        "order_id", "sales_channel", "order_status"
    ]],
    on="order_id", how="left"
)

channel_summary = (
    sales_analysis
    .groupby("sales_channel")
    .agg(
        gross_line_revenue=("line_revenue", "sum"),
        average_line_revenue=("line_revenue", "mean"),
        line_items=("order_item_id", "count"),
        orders=("order_id", "nunique")
    )
    .sort_values(
        "gross_line_revenue", ascending=False
    )
)

print(channel_summary)

               gross_line_revenue  average_line_revenue  line_items  orders
sales_channel
Web                    2324877.34            199.972247       11626    4885
Marketplace            2312808.93            198.337101       11661    4961
Mobile App             2290206.85            197.007041       11625    4912

In [252]:
items_analysis

,order_item_id,order_id,product_id,quantity,unit_price_at_purchase,purchase_price_num,unit_cost,category_clean,line_revenue,line_cost
0,ITEM000000001,ORD0000001,PROD00513,2,120.67,120.67,71.15,Sports,241.34,142.3
1,ITEM000000002,ORD0000002,PROD00124,2,83.58,83.58,63.11,Beauty,167.16,126.22
2,ITEM000000003,ORD0000002,PROD00631,2,46.96,46.96,30.08,Electronics,93.92,60.16
3,ITEM000000004,ORD0000002,PROD00136,1,100.59,100.59,55.82,Groceries,100.59,55.82
4,ITEM000000005,ORD0000002,PROD00090,1,109.18,109.18,74.36,Home & Kitchen,109.18,74.36
...,...,...,...,...,...,...,...,...,...,...
34907,ITEM000037496,ORD0014999,PROD00194,1,69.64,69.64,56.45,Home & Kitchen,69.64,56.45
34908,ITEM000037497,ORD0014999,PROD00000,1,63.45,63.45,<NA>,<NA>,63.45,<NA>
34909,ITEM000037498,ORD0014999,PROD00138,1,128.96,128.96,96.76,Toys,128.96,96.76
34910,ITEM000037500,ORD0015000,PROD00376,2,208.44,208.44,124.37,Beauty,416.88,248.74
34911,ITEM000037501,ORD0015000,PROD00584,2,63.2,63.2,40.73,Electronics,126.4,81.46

In [253]:
orders_clean

,order_id,customer_id,order_datetime,order_status,sales_channel,shipping_method,discount_pct,shipping_fee,order_datetime_clean,order_month
0,ORD0000001,CUST000839,2025-11-07 17:02:00,Cancelled,Marketplace,Standard,0.074,102.68,2025-11-07 17:02:00,2025-11
1,ORD0000002,CUST002871,09/18/2025 09:13 AM,Completed,Marketplace,Express,0.063,0.00,2025-09-18 09:13:00,2025-09
2,ORD0000003,CUST000720,2025-08-08 04:59:00,Completed,Web,Standard,0.137,103.83,2025-08-08 04:59:00,2025-08
3,ORD0000004,CUST002515,2025-10-14 12:56:00,Completed,Web,Pickup,0.005,112.69,2025-10-14 12:56:00,2025-10
4,ORD0000005,CUST001544,2024-05-30 04:56:00,Completed,Marketplace,Pickup,NaN,111.73,2024-05-30 04:56:00,2024-05
...,...,...,...,...,...,...,...,...,...,...
14995,ORD0014996,CUST003231,2025-02-24 15:40:00,Completed,Web,Pickup,0.001,47.33,2025-02-24 15:40:00,2025-02
14996,ORD0014997,CUST002061,2024-10-05 12:20:00,Completed,Web,Standard,0.078,73.77,2024-10-05 12:20:00,2024-10
14997,ORD0014998,CUST000852,2026-01-23 00:19:00,Pending,Marketplace,Standard,0.031,81.18,2026-01-23 00:19:00,2026-01
14998,ORD0014999,CUST002641,2024-08-26 00:48:00,Shipped,Web,Pickup,0.184,101.35,2024-08-26 00:48:00,2024-08
14999,ORD0015000,CUST002567,2025-07-23 09:55:00,Completed,Marketplace,Pickup,0.104,67.03,2025-07-23 09:55:00,2025-07

In [258]:
sales_analysis

,order_item_id,order_id,product_id,quantity,unit_price_at_purchase,purchase_price_num,unit_cost,category_clean,line_revenue,line_cost,sales_channel,order_status
0,ITEM000000001,ORD0000001,PROD00513,2,120.67,120.67,71.15,Sports,241.34,142.3,Marketplace,Cancelled
1,ITEM000000002,ORD0000002,PROD00124,2,83.58,83.58,63.11,Beauty,167.16,126.22,Marketplace,Completed
2,ITEM000000003,ORD0000002,PROD00631,2,46.96,46.96,30.08,Electronics,93.92,60.16,Marketplace,Completed
3,ITEM000000004,ORD0000002,PROD00136,1,100.59,100.59,55.82,Groceries,100.59,55.82,Marketplace,Completed
4,ITEM000000005,ORD0000002,PROD00090,1,109.18,109.18,74.36,Home & Kitchen,109.18,74.36,Marketplace,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...
34907,ITEM000037496,ORD0014999,PROD00194,1,69.64,69.64,56.45,Home & Kitchen,69.64,56.45,Web,Shipped
34908,ITEM000037497,ORD0014999,PROD00000,1,63.45,63.45,<NA>,<NA>,63.45,<NA>,Web,Shipped
34909,ITEM000037498,ORD0014999,PROD00138,1,128.96,128.96,96.76,Toys,128.96,96.76,Web,Shipped
34910,ITEM000037500,ORD0015000,PROD00376,2,208.44,208.44,124.37,Beauty,416.88,248.74,Marketplace,Completed
34911,ITEM000037501,ORD0015000,PROD00584,2,63.2,63.2,40.73,Electronics,126.4,81.46,Marketplace,Completed

In [260]:
items_analysis['line_profit'] = (
    items_analysis['line_revenue'] - items_analysis['line_cost']
)

In [263]:
numeric_cols = [
    "quantity",
    "purchase_price_num",
    "line_revenue",
    "unit_cost",
    "line_profit"
]

corr = sales_analysis[numeric_cols].corr()
print(corr.round(2))

                    quantity  purchase_price_num  line_revenue  unit_cost  \
quantity                 1.0                0.00          0.70       0.00
purchase_price_num       0.0                1.00          0.62       0.95
line_revenue             0.7                0.62          1.00       0.59
unit_cost                0.0                0.95          0.59       1.00
line_profit              0.6                0.63          0.94       0.52

                    line_profit
quantity                   0.60
purchase_price_num         0.63
line_revenue               0.94
unit_cost                  0.52
line_profit                1.00

In [264]:
corr

,quantity,purchase_price_num,line_revenue,unit_cost,line_profit
quantity,1.000000,0.001140,0.698421,0.002091,0.598136
purchase_price_num,0.001140,1.000000,0.617143,0.953349,0.630298
line_revenue,0.698421,0.617143,1.000000,0.591242,0.939665
unit_cost,0.002091,0.953349,0.591242,1.000000,0.517592
line_profit,0.598136,0.630298,0.939665,0.517592,1.000000

In [265]:
q1 = sales_analysis["line_revenue"].quantile(0.25)
q3 = sales_analysis["line_revenue"].quantile(0.75)
iqr = q3 - q1

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

outliers = sales_analysis[
    (sales_analysis["line_revenue"] < lower)
    | (sales_analysis["line_revenue"] > upper)
]

print(outliers[[
    "order_id", "product_id", "quantity",
    "purchase_price_num", "line_revenue"
]].head())

       order_id product_id  quantity  purchase_price_num  line_revenue
34   ORD0000012  PROD00261         5               144.3         721.5
92   ORD0000036  PROD00108         5              127.69        638.45
101  ORD0000041  PROD00695         4              217.27        869.08
108  ORD0000043  PROD00562         6               86.08        516.48
110  ORD0000045  PROD00356         6               123.8         742.8

In [266]:
outliers

,order_item_id,order_id,product_id,quantity,unit_price_at_purchase,purchase_price_num,unit_cost,category_clean,line_revenue,line_cost,line_profit,sales_channel,order_status
34,ITEM000000038,ORD0000012,PROD00261,5,144.3,144.3,94.04,Beauty,721.5,470.2,251.3,Web,Shipped
92,ITEM000000103,ORD0000036,PROD00108,5,127.69,127.69,80.81,Electronics,638.45,404.05,234.4,Mobile App,Completed
101,ITEM000000113,ORD0000041,PROD00695,4,217.27,217.27,117.38,Fashion,869.08,469.52,399.56,Web,Completed
108,ITEM000000120,ORD0000043,PROD00562,6,86.08,86.08,71.63,Books,516.48,429.78,86.7,Marketplace,Completed
110,ITEM000000123,ORD0000045,PROD00356,6,123.8,123.8,80.45,Electronics,742.8,482.7,260.1,Marketplace,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34826,ITEM000037407,ORD0014963,PROD00414,4,178.96,178.96,101.43,Sports,715.84,405.72,310.12,Marketplace,Returned
34830,ITEM000037412,ORD0014965,PROD00599,6,134.99,134.99,90.98,Home & Kitchen,809.94,545.88,264.06,Web,Shipped
34835,ITEM000037418,ORD0014968,PROD00452,3,186.71,186.71,110.01,Groceries,560.13,330.03,230.1,Web,Completed
34873,ITEM000037461,ORD0014984,PROD00090,5,109.18,109.18,74.36,Home & Kitchen,545.9,371.8,174.1,Mobile App,Completed
34898,ITEM000037486,ORD0014995,PROD00443,3,188.24,188.24,123.39,Groceries,564.72,370.17,194.55,Marketplace,Returned